export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
export VLLM_ATTENTION_BACKEND=XFORMERS

WORKING_DIR="/home/yourname/verl"
CKPTS_DIR="/data/yourname/checkpoints"
project_name='SIRL'
exp_name='partialKL'

output_dir=$CKPTS_DIR/$project_name/$exp_name
python3 -m verl.trainer.main_ppo \
 algorithm.adv_estimator=reinforce_plus_plus \
 algorithm.use_kl_in_reward=True \
 algorithm.kl_ctrl.kl_coef=0.001 \
 data.train_files=$WORKING_DIR/trainset/gurobi_examples_OR_train.parquet \
 data.val_files=$WORKING_DIR/trainset/gurobi_examples_OR_test.parquet \
 data.train_batch_size=32 \
 data.max_prompt_length=2048 \
 data.max_response_length=8192 \
 data.filter_overlong_prompts=True \
 data.prompt_key=prompt \
 data.truncation=left \
 reward_model.reward_manager=batch \
 custom_reward_function.path='$WORKING_DIR/batch_score_gurobi.py' \
 actor_rollout_ref.model.path='/.cache/modelscope/models/Qwen/Qwen2.5-7B-Instruct' \
 actor_rollout_ref.model.use_remove_padding=True \
 actor_rollout_ref.model.enable_gradient_checkpointing=True \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.clip_ratio_low=0.20 \
 actor_rollout_ref.actor.clip_ratio_high=0.30 \
 actor_rollout_ref.actor.ppo_mini_batch_size=32 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
 actor_rollout_ref.actor.fsdp_config.param_offload=True \
 actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
 actor_rollout_ref.rollout.max_num_batched_tokens=12232 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.n=16 \
 actor_rollout_ref.ref.fsdp_config.param_offload=True \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-5 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 trainer.project_name="${project_name}" \
 trainer.experiment_name="${exp_name}" \
 trainer.logger=['console','wandb'] \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=25 \
 trainer.test_freq=1000 \
 trainer.default_local_dir=$output_dir \
 trainer.total_epochs=2 2>&1 | tee withKL.log
